### ISSUE TITLE
Title on Grove still reads "Riot"

### ISSUE THREAD

**Issue by munprix** [FabricLabs/chat.fabric.pub#4]

**Comment by martindale** [comment]
This should be resolved by [`97574695cb1c5edcccc3f8cbde5b7097dc943d28`](https://github.com/FabricLabs/matrix-react-sdk/commit/97574695cb1c5edcccc3f8cbde5b7097dc943d28) on [FabricLabs/matrix-react-sdk](https://github.com/FabricLabs/matrix-react-sdk), and is now available in the RC1 release.  Thanks!
